### ISSUE TITLE
An example of how to insert tool output into the chat history

### ISSUE THREAD

**Issue by offchan42** [Mirascope/mirascope#254]
### Description

It'd be nice if there's an example code that shows how to insert tool output back into chat history for the LLM to generate a formatted response given the tool output.

This is an example dialogue:
```yaml
user: I'd like to ask a math question
assistant: go ahead!
user: what's 123 times five thousand seven hundred?
assistant: `call_tool multiply(123, 5700)`
tool: 701100
assistant: It's 701,100. That's about seven hundred thousands!
```

Making the example more full-fledged:
1. Show how to stream messages if the chatbot decides to not use the tool. In the above dialogue, all the assistant messages should be streamed to the console, except the tool use.
2. Show how to call tools in parallel.
